export enum ExeptionInfraestructureType {
	BAD_REQUEST = "BAD_REQUEST",
	CONFLICT = "CONFLICT",
	PERSISTENCE = "PERSISTENCE",
	NOT_FOUND = "NOT_FOUND",
	UNAUTHORIZED = "UNAUTHORIZED",
	NOT_REGISTERED="NOT_REGISTERED"
}
