export enum BaseExceptionEnum{
    DOMAIN_EXCEPTION = "DOMAIN_EXCEPTION",
	APPLICATION_EXCEPTION = "APPLICATION_EXCEPTION",
	INFRAESTRUCTURE_EXCEPTION = "INFRAESTRUCTURE_EXCEPTION",
	NOT_REGISTERED="NOT_REGISTERED"
}