name: Test API

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Test API
      run: |
        echo "Starting to run the app test ..."
        pnpm install
        pnpm test
        echo "End of the test"