name: Test API

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install dependencies and run tests
      run: |
        echo "Starting the API test process..."
        echo "Installing dependencies using pnpm..."
        pnpm install
        echo "Running tests..."
        pnpm test
        echo "API test process completed."